config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: [:index, :show]
  patch 'meetings/:id/extend', to: 'meetings#extend'
  resources :meetings, only: [:new, :create, :show, :update, :destroy] do
    member do
      get "/chat", to: "meetings#chat"
      get 'howdiditgo'
      get 'share'
    end
    resources :messages, only: [:create]
    resources :locations, only: [:create, :edit]
  end
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]

  resources :pages, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :landing, only: [:index]
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]
  resources :users, only: [:create, :update]
  resources :admin, only: [:index, :show]

  get "profiles/edit", to: 'users#edit', as: :edit_profile
  get "profiles/:id", to: 'users#profile', as: :profile

  root to: "landing#index"

  get "up" => "rails/health#show", as: :rails_health_check
  get 'form_page', to: 'pages#form_page'
  get 'sessions_page', to: 'pages#sessions_page'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :friend_meetings
  has_many :friends, through: :friend_meetings
  has_many :messages
  has_many :locations

  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :start_time, presence: true
  validates :date, presence: true
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  #to instantiate the new meeting form containing who, what, where etc.
  def new
    @meeting = Meeting.new
    @friends = Friend.all
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @friends = Friend.all
    @meeting.user = current_user
    if @meeting.save
      redirect_to meeting_path(@meeting)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @friends = Friend.all
    @meeting = Meeting.find(params[:id])
    @share_code = params[:share_code]

    if @share_code && @meeting.user.share_code != @share_code
      redirect_to root_path, notice: "You are not allowed to see this meeting"
      return
    end

    if @share_code
      @no_mobile_nav = true
    end

    # question - is the geocoded.map finding a column within flats referring to geocoded.map or is it convention?
    @markers = @meeting.locations.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        marker_html: render_to_string(partial: "marker")
      }
    end
    # unless @meeting.locations.last.nil?
    #   @markers = [{
    #     lat: @meeting.locations.last.latitude,
    #     lng: @meeting.locations.last.longitude,
    #     marker_html: render_to_string(partial: "marker")
    #   }]
    # end
    @timer = @meeting.duration
  end

  # chatroom
  # def chat
  #   @meeting = Meeting.find(params[:id])
  # end

  # chatroom and code to ensure meeting privacy
  # def chat
  #   @`meeting = Meeting.find(params[:id])

  #   if @meeting.nil? || @meeting.user != current_user
  #     # User is allowed to access the meeting
  #   else
  #     # User is not allowed to access the meeting, redirect to home page
  #     redirect_to root_path, alert: "You are not authorized to access this page."
  #   end
  # end
  # chatroom and code to ensure meeting privacy
  def chat
    @meeting = Meeting.find(params[:id])

    if @meeting.nil? || @meeting.user != current_user
      # User is not allowed to access the meeting, redirect to home page
      redirect_to root_path, alert: "You are not authorized to access this page."
    else
      # User is allowed to access the meeting
    end
  end

  def extend
    @meeting = Meeting.find(params[:id])
    @meeting.update(extend_meeting_params)
  end

  #updating of the meeting information tt
  def update
    meeting = Meeting.find(params[:id])
    meeting.update(end_time: Time.now)

    render json: { message: 'Thanks for telling us you are safe'}
  end

  # will this allow the user to cancel a future meeting?
  def cancel
    # Check that meeting start_time is before Time.zone.now (current_time) before deleting
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to meeting_path, status: :see_other
  end

  def howdiditgo
    @meeting = Meeting.find(params[:id])
  end

  private

  def meeting_params
    params.require(:meeting).permit(:start_time, :end_time, :date, :who, :what, :initial_meet_location, :latitude, :longitude, :fake_call, :how_did_it_go, :duration, friend_ids: [])
  end

  def extend_meeting_params
    params.require(:meeting).permit(:duration)
  end
end

app/views/meetings/_marker.html.erb
<%= image_tag "icon.png", height: 30, width: 30, alt: "map icon" %>

app/views/meetings/chat.html.erb
   <div class="d-flex justify-content-center align-items-center" >
      <%= link_to meeting_path(@meeting), class: 'btn form-submit select-btn mb-3', style: "padding-top: 25px;" do %>
        <i class="fa-solid fa-arrow-left text-success fs-1 ms-5 border border-success p-2 top-back-button"></i>
    <% end %>
    <h1 class="text-white mt-4 mb-4 text-center fw-light heading">
    <%= image_tag 'Star 2.svg' %>
    chat with us
    </h1>
   </div>

<div class="container chat" id="chat" data-controller="meeting-chat" data-meeting-chat-meeting-id-value="<%= @meeting.id %>">
  <%# <h1>Meeting with <%= current_user.email %>

  <div class="messages" data-meeting-chat-target="messages">
    <%#= @meeting.messages %>
    <% @meeting.messages.each do |message| %>
      <%# <% if message.user = current_user  %>
        <%= render 'messages/message', message: message %>
      <%# <% end %>
    <% end %>
  </div>

  <%= simple_form_for [ @meeting, Message.new ], remote: true, html: { data: { 'meeting-chat-target': "form" } } do |form| %>
    <div class="form-group position-relative">
      <%= form.text_area :content, rows: 3, class: "form-control mb-3 rounded-box txt", data: { 'meeting-chat-target': "input" }, placeholder: "Type a message..." %>
      <%= form.submit "Send", class: 'btn btn-outline-success form-submit message-sent-button select-btn mb-3 w-25', data: { action: "meeting-chat#submit" } %>
    </div>
  <% end %>
</div>

<div class="spacer"></div>

app/views/meetings/howdiditgo.html.erb
<div class="container p-3 mt-3" data-controller="howdiditgo">
  <div class="d-flex justify-content-center">
    <%= image_tag "CHAPERONELOGO_ALPHA 4.svg", class:"mt-3 mb-4 " %>
  </div>

  <h1 class="text-white fw-light fs-2 mb-4 text-start heading">how did it go?</h1>
  <div class="d-flex gap-3 p-3 mb-5 rounded-5 face-buttons ">
    <button class="btn flex-grow-1 rounded-3" data-action="click->howdiditgo#togglecardgood">
      <i class="fa-regular fa-face-smile text-success face"></i>
    </button>
    <button class="btn flex-grow-1 rounded-3" data-action="click->howdiditgo#togglecardok">
      <i class="fa-regular fa-face-meh face text-white"></i>
    </button>
    <button class="btn flex-grow-1 rounded-3" data-action="click->howdiditgo#togglecardbad">
      <i class="fa-regular fa-face-frown text-danger face"></i>
    </button>
  </div>

<div class="card-area" data-howdiditgo-target="cardarea">

  <%# <button class="btn flex-grow-1 rounded-3" data-action="click->howdiditgo#togglecard"> <i class="fa-regular fa-face-smile text-success face"></i></button>
  <button class="btn flex-grow-1 rounded-3"> <i class="fa-regular fa-face-meh face text-white"></i></button>
  <button class="btn flex-grow-1 rounded-3"><i class="fa-regular fa-face-frown text-danger face"></i></button> %>
  <div class="card d-flex bg-success rounded-5 d-none" data-howdiditgo-target="cardgood">
    <h4 class="mb-4">great! see you again soon</h4>
    <i class="fa-regular fa-face-smile-wink card-icon text-end text-primary"></i>
  </div>

  <div class="card d-flex bg-warning rounded-5 d-none text-white fw-light" data-howdiditgo-target="cardok">
    <h4 class="mb-5">sorry to hear that, would you like to chat?</h4>
    <p class="fs-4 text-end btn btn-outline-light rounded-pill py-4 px-5">chat now <i class="ms-2 fa-regular fa-message text-end text-white fs-2"></i></p>
  </div>

  <div class="card d-flex bg-info rounded-5 d-none text-white" data-howdiditgo-target="cardbad">
    <h4 class="mb-3 fw-light">that must of been difficult for you, we are here to support you.</h4>
    <h4 class="mb-4 text-white">contact us below:</h4>
    <div class="d-flex"></div>
    <p class="fs-4 text-end btn btn-outline-light rounded-pill py-4 px-5">chat now <i class="ms-2 fa-regular fa-message text-end text-primary fs-2"></i></p>
    <p class="fs-4 text-start btn btn-outline-light rounded-pill py-4 px-5"><i class="fa-solid fa-phone me-3 text-primary fs-3"></i>call now </p>
  </div>
</div>
<div class="spacer"></div>

</div>

app/views/meetings/new.html.erb
<div class="container p-3 mt-3" data-controller="inputstyling share" data-meeting-id="<%= @meeting.id %>">
  <h1 class="text-white mb-4 text-center fw-light">  <%= image_tag 'Star 2.svg' %> tell us more</h1>

<div class="container p-3 mt-3">
    <h1 class="text-white mb-4 text-center fw-light">  <%= image_tag 'Star 2.svg' %> new</h1>
  <%= simple_form_for @meeting, html: { class: 'form-horizontal' } do |f| %>
    <div class="meeting-form-group">
      <%= f.input :who, placeholder: 'Jessie Rodgers', input_html: { class: 'meeting-form-control border-0 rounded-pill control' }, label_html: {class: "meeting-form-label"} %>
    </div>

    <div class="meeting-form-group">
      <%= f.input :what, placeholder: 'Heading home...', input_html: { class: 'meeting-form-control border-0 rounded-pill control' }, label_html: {class: "meeting-form-label"} %>
    </div>

    <div class="meeting-form-group">
      <%= f.input :start_time, html5: true, input_html: { class: 'meeting-form-control border-0 rounded-pill control', data: { "inputstyling-target": "input", "action": "change->inputstyling#updateColor" } },  label_html: { class: 'meeting-form-label' } %>
    </div>

    <div class="meeting-form-group">
      <%= f.input :duration, as: :select, collection: options_for_meeting_duration, input_html: { class: 'meeting-form-control border-0 rounded-pill control', data: { "inputstyling-target": "input", "action": "change->inputstyling#updateColor" } }, label_html: { class: 'meeting-form-label' }, selected: 0 %>
    </div>

    <div class="meeting-form-group">
      <%= f.input :date, html5: true, input_html: { class: 'meeting-form-control border-0 rounded-pill control', data: { "inputstyling-target": "input", "action": "change->inputstyling#updateColor" } },  label_html: { class: 'meeting-form-label ' }   %>
    </div>

    <div class="meeting-form-group">
      <%= f.input :initial_meet_location, input_html: { class: 'meeting-form-control border-0 rounded-pill control', placeholder: "1 Rosoman Street"},  label_html: { class: 'meeting-form-label' } %>
    </div>

    <%#= f.association :friends, as: :check_boxes, legend_tag: false, input_html: { class: "friend-selector" }, item_wrapper_class: 'friend-item' %>

    <div class="meeting-form-group">

      <div class="share-friends meeting-form-group control">
        <p class="text-white fw-light full-width-header">who is allowed to follow you?</p>

        <%= f.input :friends, as: :check_boxes, legend_tag: false, collection: @friends.map { |friend| ["<img class='avatar-large item share-icon' alt='avatar-large' src=#{friend.image_url.present? ? friend.image_url : asset_path('avatar.jpeg')} />".html_safe, friend.id]} , input_html: { class: "friend-selector", name: 'meeting[friend_ids][]' }, item_wrapper_class: 'friend-item' %>

      </div>
    </div>


    <div class="meeting-form-group">
      <%# <button class="btn btn-outline-success w-100 rounded-pill form-submit select-btn" data-bs-toggle="modal" data-bs-taget="#exampleModal">Submit</button> %>



  <%= f.submit 'hook me up', class: 'btn btn-outline-success w-100 rounded-pill form-submit select-btn', data: { bs_toggle: "modal", bs_target: "#exampleModal" } %>

</div>

    </div>


  <% end %>
</div>

<div class="spacer"></div>

app/views/meetings/show.html.erb
<div class="container p-3 pb-0 mt-3" <%= %(data-controller=meeting-locations) unless @share_code %> data-meeting-locations-meeting-value="<%= @meeting.id %>" data-meeting-locations-url-value="<%= meetings_url %>">
  <div data-controller="session">
    <h1 class="text-white mb-4 text-center fw-light">
      <%= image_tag 'Ellipse 6.svg', data: {session_target: "image"}, class: "initial" %>
      meet-up
    </h1>
  </div>

  <% if @share_code %>
    <h2 class="text-white">you are following <%= @meeting.user.first_name %></h2>
    <hr class="text-white">
  <% end %>

  <% if !@share_code %>
    <div data-controller="countdown" data-countdown-duration-value="<%= @meeting.duration %>" data-countdown-meeting-id-value=" <%= @meeting.id %>">

      <h2 class="countdown mb-3" data-countdown-target="timer"></h2>
         <%= link_to do %>
      <div class="d-flex justify-content-center">



        <button class="extend-button-link btn btn-success bg-success border-none mb-3 fifteen-btn text-primary" id="need-more-time" data-action="click->countdown#extendSession">

          <div class="d-flex align-items-center justify-content-center">
            <span class="text-danger"><i class="fa-solid fa-plus plus-icon me-1"></i></span>
            <span class="fs-4 fw-bold"> 15</span>
          </div>
        </button>

      </div>

      </div>
      <% end %>
      <div class="d-flex need-time fw-bold">
        <p class="click-me text-white "><i class="fa-solid fa-arrow-left text-danger"></i> more time? </p>
      </div>
    </div>
      <% end %>
    </div>

<div class="container">

  <% if @share_code %>
  <% raise %>
    <h2 class="text-white fw-light mb-3"><%= @meeting.user.first_name %>'s route:</h2>
  <% elsif !@share_code %>
    <h2 class="text-white fw-light mb-3">your live location</h2>
  <% end %>
</div>

<div class="map mb-3"
    id="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-map-meeting-user-id-value='<%= @meeting.user.id %>'
    data-map-current-user-id-value='<%= current_user ? current_user.id : nil %>'>
</div>

<% if !@share_code %>
  <div class="container p-3 mt-3">
    <h2 class="text-white fw-light">following</h2>
    <div class="share-friends d-flex flex-column form-group p-4">
      <div>
        <p class="text-white fw-light">click below to share your personal link:</p>
      </div>
      <div class="grid">
        <div class="text-white fs-light friend_name">
          <div class="avatar-custom item default-icon border d-flex justify-content-center align-items-center text-white fw-light">
            C<i class="fa-solid fa-check"></i>
          </div>
          <p class="text-white fw-light mt-2">chaperone</p>
        </div>
        <% @meeting.friends.each do |friend| %>
          <%= link_to "https://wa.me/?text=Link to follow #{@meeting.user.first_name}: #{meeting_url(@meeting)}?share_code=#{@meeting.user.share_code} Do not share this link", target: "_blank" do %>
            <div class="text-white friend_name avatar-friend text-center">
              <%= image_tag friend.image_url, class: "item share-icon default-icon avatar-custom" %>
              <i class="fa-solid fa-check"></i>
              <p class="text-white fs-light mt-2"><%= friend.name %></p>
            </div>

          <% end %>
        <% end %>
      </div>
    </div>

    <div class="buttons d-flex gap-2 mb-3">

      <div class="meeting-btn bg-danger text-white d-flex align-items-center justify-content-center p-3 text" data-bs-toggle="modal" data-bs-target="#sosModal">SOS</div>

    <div class="meeting-btn bg-success flex-grow-1 text-white d-flex align-items-center justify-content-center p-3">
      <%= link_to howdiditgo_meeting_path do %>
    <div class="text text-primary" id="safe-button">safe</div>
      <% end %>
    </div>
    <%= link_to chat_meeting_path(@meeting), class: 'meeting-btn bg-warning text-white d-flex align-items-center justify-content-center p-3' do %>
      <div class="text text-center">it's getting <br>weird</div>
        <% end %>
      </div>
    <% else %>
  <div class="container p-3 mt-3">
    <p class="text-white">this is your personal page to follow <%= @meeting.user.first_name %></p>
  </div>
<% end %>
<%= render "shared/sos_modal" %>
</div>
    <div class="spacer"></div>

app/views/meetings/update.html.erb
<%# for updating the information provided for the session %>
<%= simple_form_for @meeting do |f| %>
  <%= f.input :start_time, html5: true %>
  <%= f.input :end_time, html5: true %>
  <%= f.input :date, html5: true %>
  <%= f.input :who %>
  <%= f.input :what %>
  <%= f.input :initial_meet_location %>
  <%= f.submit %>
<% end %>