config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: [:index, :show]
  patch 'meetings/:id/extend', to: 'meetings#extend'
  resources :meetings, only: [:new, :create, :show, :update, :destroy] do
    member do
      get "/chat", to: "meetings#chat"
      get 'howdiditgo'
      get 'share'
    end
    resources :messages, only: [:create]
    resources :locations, only: [:create, :edit]
  end
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]

  resources :pages, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :landing, only: [:index]
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]
  resources :users, only: [:create, :update]
  resources :admin, only: [:index, :show]

  get "profiles/edit", to: 'users#edit', as: :edit_profile
  get "profiles/:id", to: 'users#profile', as: :profile

  root to: "landing#index"

  get "up" => "rails/health#show", as: :rails_health_check
  get 'form_page', to: 'pages#form_page'
  get 'sessions_page', to: 'pages#sessions_page'
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  has_many :friend_meetings, dependent: :destroy
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]

  # GET /friends
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  def create
    @friend = Friend.new(friend_params)
    @friend.user = current_user
    if @friend.save
      redirect_to @friend, notice: 'Friend was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /friends/1
  def update
    if @friend.update(friend_params)
      redirect_to @friend, notice: 'Friend was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /friends/1
  def destroy
    @friend.destroy
    redirect_to friends_url, notice: 'Friend was successfully deleted.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:email)
    end
end

app/views/friends/_form.html.erb
<%= simple_form_for @friend do |form| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% @friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :email %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Friends</h1>

<%= link_to 'New Friend', new_friend_path %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.email %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<h1>Friend</h1>

<p>
  <strong>Primary User:</strong>
  <%= @friend.email %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>