config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: [:index, :show]
  patch 'meetings/:id/extend', to: 'meetings#extend'
  resources :meetings, only: [:new, :create, :show, :update, :destroy] do
    member do
      get "/chat", to: "meetings#chat"
      get 'howdiditgo'
      get 'share'
    end
    resources :messages, only: [:create]
    resources :locations, only: [:create, :edit]
  end
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]

  resources :pages, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :landing, only: [:index]
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]
  resources :users, only: [:create, :update]
  resources :admin, only: [:index, :show]

  get "profiles/edit", to: 'users#edit', as: :edit_profile
  get "profiles/:id", to: 'users#profile', as: :profile

  root to: "landing#index"

  get "up" => "rails/health#show", as: :rails_health_check
  get 'form_page', to: 'pages#form_page'
  get 'sessions_page', to: 'pages#sessions_page'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings
  has_many :friends, dependent: :destroy
  has_many :messages

  before_save :generate_share_code

  def generate_share_code
    self.share_code = SecureRandom.urlsafe_base64(nil, false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
  end

  def edit
    @user = current_user
  end
end

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :date_of_birth %>
  <%= f.input :mobile_number %>
  <%= f.input :address %>
  <%= f.input :gender %>
  <%= f.input :sexuality %>
  <%= f.submit %>
<% end %>

app/views/users/profile.html.erb
<%= @user.first_name %>

<%= link_to "edit personal details", edit_profile_path %>

<%# <%= link_to "add trusted friend", profile_path(current_user) %>

<%= link_to "My trusted friends", friends_path %>