config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: [:index, :show]
  patch 'meetings/:id/extend', to: 'meetings#extend'
  resources :meetings, only: [:new, :create, :show, :update, :destroy] do
    member do
      get "/chat", to: "meetings#chat"
      get 'howdiditgo'
      get 'share'
    end
    resources :messages, only: [:create]
    resources :locations, only: [:create, :edit]
  end
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]

  resources :pages, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :landing, only: [:index]
  resources :friends
  resources :friend_meetings, only: [:create, :destroy]
  resources :users, only: [:create, :update]
  resources :admin, only: [:index, :show]

  get "profiles/edit", to: 'users#edit', as: :edit_profile
  get "profiles/:id", to: 'users#profile', as: :profile

  root to: "landing#index"

  get "up" => "rails/health#show", as: :rails_health_check
  get 'form_page', to: 'pages#form_page'
  get 'sessions_page', to: 'pages#sessions_page'
end

app/views/shared/_callmodal.erb
<div class="modal fade " id="callModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered ">
    <div class="modal-content call-card">
      <div class="modal-header p-0 mb-4 mt-4">
        <h1 class="modal-title fs-3 text-center fw-light " id="exampleModalLabel">incoming call</h1>
        <button type="button" class="btn fs-4" data-bs-dismiss="modal" aria-label="Close" id="close"><i class="fa-solid fa-x"></i></button>
      </div>
      <div class="modal-body d-flex justify-content-center align-items-center pb-3">
        <i class="fa-solid fa-phone-volume text-white phone-call mb-3"></i>
      </div>
      <div class="modal-footer p-0">
<%#
        <button type="button" class="btn btn-danger rounded-pill px-4 py-3 w-100 mt-5 confirm-call text-white">close</button> %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-controller="session" data-session-target="image">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-controller="session" data-session-target="image">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_mobile_nav.html.erb
  <div class="navbar d-flex justify-content-around bg-warning text-primary">

    <div class="" data-controller="call">

      <i class="fa-solid fa-phone fs-4" data-bs-toggle="modal" data-bs-target="#callModal"></i>
    </div>
     <%= link_to pages_path do%>
    <div class=""> <i class="fa-solid fa-house fs-4"></i> </div>
      <% end %>

    <% if @meeting.nil? || @meeting.id == nil %>
    <div  class=""><i class="fa-regular fa-message fs-4"></i></div>
      <% else %>
      <%= link_to chat_meeting_path(@meeting) do%>
    <div  class=""><i class="fa-regular fa-message fs-4"></i></div>
      <% end %>
      <% end %>

  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to "my profile", profile_path(current_user) if user_signed_in? %>
</div>

app/views/shared/_new_session_modal.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content p-5 call-card">
      <div class="modal-header custom-model-border">
        <h1 class="modal-title fw-light fs-5" id="exampleModalLabel">remember</h1>
        <button type="button" class="btn fs-4" data-bs-dismiss="modal" aria-label="Close" id="close"><i class="fa-solid fa-x"></i></button>
      </div>
      <div class="modal-body p-0">
        <div class="chat-box  modal-box d-flex px-2 justify-content-center ">
          <p class="me-4 pt-4 pb-3 content-width fw-light">we are here to chat anytime</p>
          <i class="fa-regular fa-message fs-2 pt-4 pb-3"></i>

        </div>
        <div class="load-box modal-box d-flex px-2 justify-content-center">
          <div class="d-flex justify-content-center align-items-center">
             <i class="fa-solid fa-spinner fs-1"></i>
          </div>

            <p class="ms-4 pt-4 pb-3 content-width fw-light">load app during your meeting</p>
        </div>
        <div class="call-box modal-box d-flex px-2 justify-content-center">

          <p class="me-4 pt-4 pb-3 content-width fw-light">recieve a fake call</p>
          <div class="d-flex justify-content-center align-items-center">
            <i class="fa-solid fa-phone-volume fs-2"></i>
          </div>
        </div>
        <div class="have-fun-box d-flex px-2 justify-content-center">
                    <i class="fa-regular fa-face-smile-wink fs-1 pt-4 pb-3"></i>
          <p class="ms-4 pt-4 pb-3 content-width fw-light">have fun</p>

        </div>
      </div>
      <div class="modal-footer footer-border">

        <%= f.submit 'Submit', class: 'btn btn-outline-success w-100 rounded-pill form-submit select-btn' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sos_modal.erb
<div class="modal fade " id="sosModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered ">
    <div class="modal-content call-card">
      <div class="modal-header p-0 mb-4 mt-4">
        <h1 class="modal-title fs-3 text-center text-danger  " id="exampleModalLabel">emergency call</h1>

      </div>
      <div class="modal-body d-flex justify-content-center align-items-center pb-3">
        <i class="fa-solid fa-phone-volume text-white phone-call mb-3"></i>
      </div>
      <div class="modal-footer p-0 d-flex justify-content-center">
        <div class="d-flex gap-3 justify-content-center mt-4">
                  <button type="button" class="btn btn-success px-4 py-3 w-100 confirm-call text-primary rounded-4">call now</button>
        <button type="button" class="btn btn-outline-danger px-4 py-3 w-100 confirm-call text-danger rounded-4" data-bs-dismiss="modal" aria-label="Close">close</button>


        </div>
      </div>
    </div>
  </div>
</div>